site_name: Mark Gravestock
site_description: A personal knowledge log
site_url: https://markgravestock.github.io/personal-site/

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.tabs
    - navigation.indexes
    - search.suggest
    - search.highlight

plugins:
  - search
  - tags
  - meta
  - awesome-pages
  - blog:
      blog_dir: blog


markdown_extensions:
  - admonition
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MarkGravestock
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/YOUR-LINKEDIN-SLUG

exclude_docs: |
  superpowers/

validation:
  nav:
    omitted_files: ignore
